In [28]:
#NumPy – Day 1 Assignment
#Introduction to NumPy

# Question 1: Student Marks Array
# Create a NumPy array containing the marks of 10 students.
# Display:
# ● Complete array
# ● Data type
# ● Total number of elements

# import numpy as np
# marks=np.array([ 78, 85, 90, 67, 88, 92, 75, 81, 69, 95])
# print("Complete Array:",marks)
# print("DataType:",marks.dtype)
# print("Total No of Elements:",marks)


# Question 2: Employee IDs
# Create a NumPy array of employee IDs.
# 101, 102, 103, 104, 105, 106
# Display:
# ● Array
# ● Number of dimensions
# ● Shape

# import numpy as np
# employee_ids=np.array([101,102,103
#                       ,104,105])
# print("Array:",employee_ids)
# print(employee_ids.ndim)
# print(employee_ids.shape)


# Question 3: College Students Data (2D
# Array)
# Create the following 2D array.
# 78 82 90
# 65 70 88
# 91 86 79
# Display:
# ● Complete array
# ● Shape
# ● Size
# ● Data type

# import numpy as np
# students=np.array([
#     [78,82,90],
#     [65,70,88],
#     [91,86,79]
# ])  
# print("2D Array:",students)
# print(students.shape)
# print(students.size)
# print(students.dtype)

# Question 4: Zero Matrix
# Create a 5 × 5 Zero Matrix using NumPy.
# Display the matrix.

# import numpy as np
# zero_matrix = np.zeros((5, 5))
# print("5 x 5 Zero Matrix:")
# print(zero_matrix)


# Question 5: Ones Matrix
# Create a 4 × 6 Ones Matrix using NumPy.
# Display the matrix.

# import numpy as np
# ones_matrix = np.ones((4,6))
# print("4 x 6 ones Matrix:")
# print(ones_matrix)


# Question 6: Identity Matrix
# Create a 6 × 6 Identity Matrix using NumPy

# import numpy as np
# identity_matrix = np.eye(6)
# print("6 x 6 Identity Matrix:")
# print(identity_matrix)


# Question 7: Full Matrix
# Create a 4 × 4 matrix in which every element is 25.
# Display the matrix

# import numpy as np
# data=np.full((4,4),25)
# print(data)

# Question 8: arange()
# Create the following arrays using np.arange()
# Array 1
# 1 2 3 4 5 6 7 8 9 10
# Array 2
# 10 20 30 40 50 60 70 80 90 100
# Display both arrays.

# import numpy as np

# array1 = np.arange(1, 11)

# array2 = np.arange(10, 101, 10)

# print("Array 1:")
# print(array1)
# print("\nArray 2:")
# print(array2)


# Question 9: linspace()
# Create an array containing 8 equally spaced values between 0 and 100 using
# np.linspace().
# Display the array.

# import numpy as np
# data=np.linspace(0,100,8)
# print(data)


# Question 10: Complete Array Properties
# Create the following array.
# 10 20 30
# 40 50 60
# 70 80 90
# Display the following properties:
# ● Number of Dimensions (ndim)
# ● Shape (shape)
# ● Size (size)
# ● Data Type (dtype)

# import numpy as np

# Create the 2D array
# arr = np.array([[10, 20, 30],
#                 [40, 50, 60],
#                 [70, 80, 90]])

# Display the array
# print("Array:")
# print(arr)

# Display properties
# print("\nNumber of Dimensions:", arr.ndim)
# print("Shape:", arr.shape)
# print("Size:", arr.size)
# print("Data Type:", arr.dtype)

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Number of Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
